### ISSUE TITLE
Article items aren't aligned with pictures

### ISSUE THREAD

**Issue by farishkash** [olow/capstone#2]
You need to do some flex adjustments here, the text is above the picture inside of being lined up with it.

<img width="810" alt="colmar1" src="https://user-images.githubusercontent.com/5844161/41571281-4f493a1c-7327-11e8-9526-f75d82b6315c.png">

Even though it doesn't match the spec, it looks better if you change flex-start to center in your align-items.

**Comment by olow** [comment]
ok, fixed it
