### ISSUE TITLE
Video blank

### ISSUE THREAD

**Issue by farishkash** [olow/capstone#3]
The system can't find poster file so the video won't load.  

<img width="1030" alt="colmar2" src="https://user-images.githubusercontent.com/5844161/41571440-07f6f482-7328-11e8-8cc4-8561c2162345.png">

Once I reviewed the post attribute the video worked.

` <video src="res/video/thesis.mp4" autoplay poster="posterimage.jpg" /></video>`

**Comment by olow** [comment]
ok, i removed the poster attribute since there is no asset. the first frame of the video should be shown as default now.
